"""EchoAuth reference runtime skeleton.

This package exposes implementation interfaces generated from the approved
specifications and contracts. It intentionally contains no governance,
authorization, policy, audit, or execution business logic.
"""

from echoauth.config import ContractPaths, RuntimeConfig
from echoauth.events import EventBus, EventEnvelope
from echoauth.interfaces import (
    AuditService,
    AuthorityService,
    DelegationService,
    EmergencyOverrideService,
    EnvelopeService,
    EscalationService,
    ExecutionClaimService,
    HaltService,
    IdentityService,
    InvariantService,
    NotificationService,
    PolicyService,
    RecoveryService,
    RefusalService,
    RuntimeService,
    TokenService,
)
from echoauth.main import EchoAuthRuntime, EchoAuthRuntimeDependencies
from echoauth.models import (
    ActorType,
    AssuranceLevel,
    AuditRecord,
    AuthorityResolutionRequest,
    AuthorityVerdict,
    CanonicalJsonObject,
    EchoAuthRequest,
    EchoAuthResult,
    ExecutionToken,
    IdentityResolutionRequest,
    IdentityVerdict,
    RuntimeEnvelope,
    RuntimeState,
)
from echoauth.repositories import (
    AuditLogRepository,
    AuthorityRegistryRepository,
    DelegationRepository,
    PolicyRegistryRepository,
    Repository,
    RevocationRepository,
    RuntimeStateRepository,
)
from echoauth.wiring import RUNTIME_DEPENDENCY_GRAPH, RuntimeDependencyEdge

__all__ = [
    "ActorType",
    "AssuranceLevel",
    "AuditLogRepository",
    "AuditRecord",
    "AuditService",
    "AuthorityRegistryRepository",
    "AuthorityResolutionRequest",
    "AuthorityService",
    "AuthorityVerdict",
    "CanonicalJsonObject",
    "ContractPaths",
    "DelegationRepository",
    "DelegationService",
    "EchoAuthRequest",
    "EchoAuthResult",
    "EchoAuthRuntime",
    "EchoAuthRuntimeDependencies",
    "EmergencyOverrideService",
    "EnvelopeService",
    "EscalationService",
    "EventBus",
    "EventEnvelope",
    "ExecutionClaimService",
    "ExecutionToken",
    "HaltService",
    "IdentityResolutionRequest",
    "IdentityService",
    "IdentityVerdict",
    "InvariantService",
    "NotificationService",
    "PolicyRegistryRepository",
    "PolicyService",
    "RUNTIME_DEPENDENCY_GRAPH",
    "RecoveryService",
    "RefusalService",
    "Repository",
    "RevocationRepository",
    "RuntimeConfig",
    "RuntimeDependencyEdge",
    "RuntimeEnvelope",
    "RuntimeService",
    "RuntimeState",
    "RuntimeStateRepository",
    "TokenService",
]
