"""Abstract service interfaces for the EchoAuth runtime skeleton."""

from __future__ import annotations

from abc import ABC, abstractmethod

from echoauth.models import (
    AuditRecord,
    AuditRecordResult,
    AuthorityResolutionRequest,
    AuthorityVerdict,
    EchoAuthRequest,
    EchoAuthResult,
    ExecutionToken,
    IdentityResolutionRequest,
    IdentityVerdict,
    RuntimeEnvelope,
)


class RuntimeService(ABC):
    """Runtime boundary.

    Specification: specs/echoauth-spec.md
    Contract: contracts/service-contracts.yaml#echoauth_runtime
    State machine: specs/runtime-state-machine.md
    """

    @abstractmethod
    def submit(self, request: EchoAuthRequest) -> EchoAuthResult:
        """Submit a runtime request."""


class IdentityService(ABC):
    """Identity resolution boundary."""

    @abstractmethod
    def resolve(self, request: IdentityResolutionRequest) -> IdentityVerdict:
        """Resolve actor identity."""


class AuthorityService(ABC):
    """Authority resolution boundary."""

    @abstractmethod
    def resolve(self, request: AuthorityResolutionRequest) -> AuthorityVerdict:
        """Resolve request authority."""


class DelegationService(ABC):
    """Delegation validation boundary."""

    @abstractmethod
    def validate(self, request: object) -> object:
        """Validate a delegation request.

        Concrete request/result models are generated only when the
        corresponding specification defines their non-object fields.
        """


class PolicyService(ABC):
    """Policy evaluation boundary."""

    @abstractmethod
    def evaluate(self, request: object) -> object:
        """Evaluate policy."""


class InvariantService(ABC):
    """Invariant validation boundary."""

    @abstractmethod
    def validate(self, request: object) -> object:
        """Validate invariants."""


class EscalationService(ABC):
    """Escalation engine boundary.

    Specification: specs/escalation-engine.md
    Contract: contracts/service-contracts.yaml, contracts/ambiguities.md
    State machine: specs/runtime-state-machine.md
    """

    @abstractmethod
    def escalate(self, request: object) -> object:
        """Escalate a request.

        Canonical evidence and context objects are typed at the contract layer;
        nested business schemas are not generated by this interface.
        """


class RefusalService(ABC):
    """Refusal engine boundary.

    Specification: specs/refusal-engine.md
    Contract: contracts/service-contracts.yaml, contracts/ambiguities.md
    State machine: specs/runtime-state-machine.md
    """

    @abstractmethod
    def refuse(self, request: object) -> object:
        """Evaluate refusal controls."""


class EnvelopeService(ABC):
    """Runtime envelope boundary."""

    @abstractmethod
    def create(self, envelope: RuntimeEnvelope) -> object:
        """Create or register a runtime envelope."""


class TokenService(ABC):
    """Execution token boundary."""

    @abstractmethod
    def issue(self, token: ExecutionToken) -> object:
        """Issue an execution token."""


class ExecutionClaimService(ABC):
    """Execution claim boundary."""

    @abstractmethod
    def claim(self, request: object) -> object:
        """Claim an execution token."""


class AuditService(ABC):
    """Audit append boundary."""

    @abstractmethod
    def append(self, record: AuditRecord) -> AuditRecordResult:
        """Append an audit record."""


class HaltService(ABC):
    """Runtime halt boundary.

    Specification: specs/runtime-halt-model.md
    Contract: contracts/service-contracts.yaml, events/event-catalog.yaml
    State machine: specs/runtime-state-machine.md
    """

    @abstractmethod
    def halt(self, request: object) -> object:
        """Halt a runtime session or request."""


class RecoveryService(ABC):
    """Runtime recovery boundary.

    Specification: specs/runtime-recovery.md
    Contract: contracts/service-contracts.yaml, database/schema.sql
    State machine: specs/runtime-state-machine.md
    """

    @abstractmethod
    def recover(self, request: object) -> object:
        """Recover runtime state."""


class EmergencyOverrideService(ABC):
    """Emergency override boundary.

    Specification: specs/emergency-override-controls.md
    Contract: contracts/service-contracts.yaml, contracts/ambiguities.md
    State machine: specs/runtime-state-machine.md
    """

    @abstractmethod
    def request_override(self, request: object) -> object:
        """Request an emergency override."""


class NotificationService(ABC):
    """Notification contract boundary.

    Specification: specs/notification-contracts.md
    Contract: events/event-catalog.yaml, contracts/integration-contracts.yaml
    State machine: not applicable
    """

    @abstractmethod
    def notify(self, request: object) -> object:
        """Send or enqueue a notification."""
