"""Delegation validation interface exports.

Specification: specs/delegation-validation.md
Contracts: contracts/service-contracts.yaml#delegation_validator,
contracts/ambiguities.md
State machine: specs/runtime-state-machine.md

Delegation evidence and scope use canonical JSON object contracts. Nested
delegation business schemas are not generated by this runtime skeleton.
"""

from echoauth.interfaces import DelegationService
from echoauth.auth.delegation_models import (
    DelegationContextMatch,
    DelegationGrant,
    DelegationHistoryEntry,
    DelegationState,
    DelegationValidationOutcome,
    DelegationValidationRequest,
    DelegationValidationResult,
    StoredDelegationGrant,
)
from echoauth.auth.delegation_repository import (
    DelegationAuditError,
    DelegationNotFoundError,
    DelegationRepository,
    DelegationRepositoryError,
    DuplicateDelegationError,
    InMemoryDelegationRepository,
    InvalidDelegationTransitionError,
)
from echoauth.auth.delegation_service import (
    DelegationContextMatcher,
    DelegationValidationAuditError,
    DelegationValidationService,
    delegation_validation_evidence_hash,
)
from echoauth.auth.delegation_validation import (
    DelegationValidationError,
    build_delegation_grant,
    delegation_evidence_hash,
    validate_delegation_grant,
    validate_delegation_request,
)

__all__ = [
    "DelegationAuditError",
    "DelegationContextMatch",
    "DelegationContextMatcher",
    "DelegationGrant",
    "DelegationHistoryEntry",
    "DelegationNotFoundError",
    "DelegationRepository",
    "DelegationRepositoryError",
    "DelegationService",
    "DelegationState",
    "DelegationValidationAuditError",
    "DelegationValidationError",
    "DelegationValidationOutcome",
    "DelegationValidationRequest",
    "DelegationValidationResult",
    "DelegationValidationService",
    "DuplicateDelegationError",
    "InMemoryDelegationRepository",
    "InvalidDelegationTransitionError",
    "StoredDelegationGrant",
    "build_delegation_grant",
    "delegation_evidence_hash",
    "delegation_validation_evidence_hash",
    "validate_delegation_grant",
    "validate_delegation_request",
]
