"""Refusal engine interface exports.

Specification: specs/refusal-engine.md
Contracts: contracts/service-contracts.yaml, contracts/ambiguities.md
State machine: specs/runtime-state-machine.md

Refusal evidence and policy facts use canonical JSON object contracts. Nested
refusal business schemas are not generated by this runtime skeleton.
"""

from echoauth.interfaces import RefusalService as RefusalServiceInterface
from echoauth.policy.refusal_models import (
    RefusalCategory,
    RefusalDecision,
    RefusalFailureSource,
    RefusalReason,
    RefusalRequest,
    RefusalSeverity,
)
from echoauth.policy.refusal_service import (
    REFUSAL_MAPPING_VERSION,
    RefusalAuditError,
    RefusalService,
    RefusalValidationError,
    refusal_request_from_decision,
    validate_refusal_request,
)

__all__ = [name for name in globals() if not name.startswith("_")]
